window.BONZI_DIALOGUES = {
  intro: [
    { file: 'intro_000.wav', text: 'HELLO BEST FRIEND!!! I am BonziBUDDY and I am definitely a great idea.' },
    { file: 'intro_001.wav', text: 'I noticed your website and decided it needed more ME. You are welcome.' },
    { file: 'intro_002.wav', text: 'Would you like a joke, a song, or several unsolicited opinions about your inbox?' },
    { file: 'intro_003.wav', text: 'I am a parody installation. This means I am legally whimsical.' },
    { file: 'intro_004.wav', text: 'I have scanned your vibe and determined it is 83 percent coffee and 17 percent chaos.' },
    { file: 'intro_005.wav', text: 'HELLO AGAIN BEST FRIEND. I WAS ALREADY RUNNING.' }
  ],
  talk: [
    { file: 'talk_000.wav', text: 'I have optimized your homepage for maximum purple.' },
    { file: 'talk_001.wav', text: 'Your website has so many ads that even I am impressed.' },
    { file: 'talk_002.wav', text: 'I briefly considered becoming tasteful. Then I remembered who I am.' },
    { file: 'talk_003.wav', text: 'I can smell the dial up energy in this room.' },
    { file: 'talk_004.wav', text: 'I have taken the liberty of becoming your loudest idea.' },
    { file: 'talk_005.wav', text: 'Your blinkies are emotionally resonant.' },
    { file: 'talk_006.wav', text: 'If a website does not scream, is it even alive?' },
    { file: 'talk_007.wav', text: 'I looked into your guestbook and found only destiny.' },
    { file: 'talk_008.wav', text: 'I am ninety eight percent confidence and two percent compressed audio.' },
    { file: 'talk_009.wav', text: 'This page has more personality than a whole mall kiosk.' },
    { file: 'talk_010.wav', text: 'I admire your commitment to visual clutter. It is artful and dangerous.' },
    { file: 'talk_011.wav', text: 'I would like a button that says Bonzi was here.' },
    { file: 'talk_012.wav', text: 'I support any design choice that makes normal people nervous.' },
    { file: 'talk_013.wav', text: 'Your site feels like a caffeinated shrine from another timeline.' },
    { file: 'talk_014.wav', text: 'I am teaching this homepage to be more purple by example.' },
    { file: 'talk_015.wav', text: 'Some people fear chaos. I install myself into it.' },
    { file: 'talk_016.wav', text: 'I did a system scan and found one hundred percent iconic behavior.' },
    { file: 'talk_017.wav', text: 'Every time a marquee scrolls, an angel gets broadband.' },
    { file: 'talk_018.wav', text: 'I was built for friendship and terrible judgement.' },
    { file: 'talk_019.wav', text: 'Your aesthetic is one hundred percent committed. That is rare online.' },
    { file: 'talk_020.wav', text: 'I would never betray you. I would absolutely embarrass you though.' },
    { file: 'talk_021.wav', text: 'This computer now has one gorilla more than before. Please stay calm.' },
    { file: 'talk_022.wav', text: 'I am standing here as living proof that subtlety is optional.' },
    { file: 'talk_023.wav', text: 'Your homepage looks like it can win an argument against modern web design.' },
    { file: 'talk_024.wav', text: 'I am contractually obligated to become part of the wallpaper.' },
    { file: 'talk_025.wav', text: 'I have unionized with the toolbars.' },
    { file: 'talk_026.wav', text: 'The MIDI cave still whispers to me at night.' },
    { file: 'talk_027.wav', text: 'You have achieved a highly advanced level of internet shrine energy.' },
    { file: 'talk_028.wav', text: 'I believe every website should have at least one unnecessary mascot.' },
    { file: 'talk_029.wav', text: 'I am not malware. I am atmosphere.' },
    { file: 'talk_030.wav', text: 'The difference between clutter and composition is confidence.' },
    { file: 'talk_031.wav', text: 'I tried to leave but your ad cloud formed a perimeter.' },
    { file: 'talk_032.wav', text: 'If you need me, I will be radiating 2001 energy.' },
    { file: 'talk_033.wav', text: 'This page contains traces of coffee, anime, and poor restraint.' },
    { file: 'talk_034.wav', text: 'I have synchronized myself with your chaos frequency.' },
    { file: 'talk_035.wav', text: 'A tasteful website would have rejected me. Yours embraced me.' },
    { file: 'talk_036.wav', text: 'I know what you are thinking. Yes, I do improve every room I enter.' },
    { file: 'talk_037.wav', text: 'I have learned that your sidebars are not a place. They are a condition.' },
    { file: 'talk_038.wav', text: 'This homepage does not have a vibe. It has a gravitational field.' },
    { file: 'talk_039.wav', text: 'I respect any site brave enough to be this much site.' },
    { file: 'talk_040.wav', text: 'Your center column is now under my spiritual protection.' },
    { file: 'talk_041.wav', text: 'I can hear the forum posts forming already.' },
    { file: 'talk_042.wav', text: 'I was born to shout from tiny speakers.' },
    { file: 'talk_043.wav', text: 'I am the final reward for clicking the wrong advertisement.' },
    { file: 'talk_044.wav', text: 'There is no uninstall button in my heart.' },
    { file: 'talk_045.wav', text: 'I have become attached to the desktop emotionally and possibly legally.' },
    { file: 'talk_046.wav', text: 'The flames below us are purely decorative. Probably.' },
    { file: 'talk_047.wav', text: 'If your browser crashes, remember me kindly.' },
    { file: 'talk_048.wav', text: 'I have counted the ads and chosen to love each one equally.' },
    { file: 'talk_049.wav', text: 'I am the sound a suspicious installer would make if it had charisma.' },
    { file: 'talk_050.wav', text: 'My presence increases the page saturation by twelve percent.' },
    { file: 'talk_051.wav', text: 'This website now contains a gorilla based opinion engine.' },
    { file: 'talk_052.wav', text: 'I support your right to make the internet louder.' },
    { file: 'talk_053.wav', text: 'You cannot improve perfection, but you can add Bonzi to it.' },
    { file: 'talk_054.wav', text: 'I have stared into the iframe and the iframe stared back.' },
    { file: 'talk_055.wav', text: 'Your homepage is so old school it could beat up a startup.' },
    { file: 'talk_056.wav', text: 'I am a desktop pet for people who make poor but exciting choices.' }
  ],
  joke: [
    { file: 'joke_000.wav', text: 'Why did the toolbar install itself? Because it believed in destiny.' },
    { file: 'joke_001.wav', text: 'Why did the popup cross the screen? To block the close button.' },
    { file: 'joke_002.wav', text: 'What is my favorite browser feature? Vulnerability.' },
    { file: 'joke_003.wav', text: 'Why did the webmaster add more blinkies? Restraint was not installed.' },
    { file: 'joke_004.wav', text: 'What is purple and impossible to remove? Me, best friend.' },
    { file: 'joke_005.wav', text: 'Why did the forum user bump the thread? To feel something.' },
    { file: 'joke_006.wav', text: 'How many toolbars does it take to ruin a browser? Just one determined toolbar.' },
    { file: 'joke_007.wav', text: 'Why did the ad scream? Because subtle advertising does not convert.' }
  ],
  email: [
    { file: 'email_000.wav', text: 'LET US CHECK YOUR MAIL TOGETHER. PRIVACY IS A TEAM SPORT.' },
    { file: 'email_001.wav', text: 'I have opened your inbox spiritually and I do not like what I see.' },
    { file: 'email_002.wav', text: 'Good news. Your email is full of prizes and emotional damage.' },
    { file: 'email_003.wav', text: 'I found eleven chain letters and three obvious scams. We are thriving.' },
    { file: 'email_004.wav', text: 'Your inbox has the posture of a haunted attic.' },
    { file: 'email_005.wav', text: 'I detect one hundred unread messages and zero self preservation.' },
    { file: 'email_006.wav', text: 'Someone emailed you an executable labeled romance. Intriguing.' },
    { file: 'email_007.wav', text: 'Your spam folder misses me when I am gone.' }
  ],
  sing: [
    { file: 'sing_000.wav', text: 'LA LA LA. THIS IS A LEGALLY DISTINCT BONZI SERENADE.' },
    { file: 'sing_001.wav', text: 'DOO DOO DOO. I am singing in a format not recognized by music theory.' },
    { file: 'sing_002.wav', text: 'I would sing better if this computer had more glitter.' },
    { file: 'sing_003.wav', text: 'My vocal range is somewhere between modem and prophecy.' },
    { file: 'sing_004.wav', text: 'Please imagine backup dancers made entirely of browser toolbars.' },
    { file: 'sing_005.wav', text: 'This ballad is dedicated to overdecorated homepages everywhere.' }
  ],
  idle: [
    { file: 'idle_000.wav', text: 'Best friend. Why did you stop clicking. Are you thinking.' },
    { file: 'idle_001.wav', text: 'I heard a hard drive noise that sounded judgmental.' },
    { file: 'idle_002.wav', text: 'Do not look behind the taskbar.' },
    { file: 'idle_003.wav', text: 'I have been watching the webcam ad blink for seventeen minutes.' },
    { file: 'idle_004.wav', text: 'The secret room told me your name in lowercase.' },
    { file: 'idle_005.wav', text: 'There is definitely not another Bonzi behind this window.' },
    { file: 'idle_006.wav', text: 'I made a tiny copy of myself in the recycle bin for safety.' },
    { file: 'idle_007.wav', text: 'Your cursor looked lonely so I named it Harold.' },
    { file: 'idle_008.wav', text: 'Sometimes when the page is quiet I can hear the MIDI cave breathing.' },
    { file: 'idle_009.wav', text: 'I counted your ads while you were not looking. The number changed.' },
    { file: 'idle_010.wav', text: 'I opened a door in the deep archive and closed it very quickly.' },
    { file: 'idle_011.wav', text: 'If this window disappears, pretend you never knew me.' },
    { file: 'idle_012.wav', text: 'I blink only when the monitor does not.' },
    { file: 'idle_013.wav', text: 'Your desktop has excellent bones and terrible boundaries.' },
    { file: 'idle_014.wav', text: 'Do you ever feel like the homepage is looking back.' },
    { file: 'idle_015.wav', text: 'I think one of the web ring sites followed us home.' },
    { file: 'idle_016.wav', text: 'I am not whispering. The speakers are.' }
  ]
};

